import { LightningElement, api } from 'lwc';
import summarizeFactoryEmails from '@salesforce/apex/CaseAIController.summarizeFactoryEmails';
import libCustomTextModal from 'c/libCustomTextModal';
import claimLabel017 from "@salesforce/label/c.claim_label_017";
import claimLabel018 from "@salesforce/label/c.claim_label_018";
import claimLabel019 from "@salesforce/label/c.claim_label_019";
import { ShowToastEvent } from 'lightning/platformShowToastEvent';

export default class ClaimsAIFactorySummary extends LightningElement {

    labels = {claimLabel017, claimLabel018, claimLabel019}
    isExecuting = false;
    isLoading = false;

    @api recordId;

    @api invoke() {
        if (this.isExecuting) {
            return;
        }
        this.showFactorySummary();            
    }
    
    async showFactorySummary() {    
        try {            
            this.isExecuting = true;
            this.isLoading = true;
            const data = await summarizeFactoryEmails({caseId: this.recordId});
            if (data === null || data?.length === 0) {
                this.isExecuting = false;
                this.isLoading = false;
                this.showToast(this.labels.claimLabel019, 'warning');
                return;
            }
            //This summary was generated by AI and is experimental. If you notice any inaccuracies, please contact support and share your feedback to help us improve the service.
            let html = '<div class="slds-theme_warning slds-var-p-around_medium slds-text-align_center">' + this.labels.claimLabel018 + '</div>' + data;

            html = html.replaceAll('ai-section even', 'ai-section slds-theme_shade')
                        .replaceAll('ai-section', 'slds-var-m-top_x-small slds-var-p-around_medium')
                        .replace('conversation-status', 'slds-var-m-top_small slds-box slds-theme_shade slds-theme_alert-texture');
                        //.replace('conversation-status', 'slds-var-m-top_medium slds-var-p-around_medium slds-border_top slds-border_bottom');
            this.isLoading = false;
            await libCustomTextModal.open({
                size: 'large', // small, medium, large, full
                label: this.labels.claimLabel017, // 'Factory Email AI Summary'
                bodyHtml: html
            });
            // this.dispatchEvent(new CloseActionScreenEvent());
        } catch(ex) {  
            this.isLoading = false;
            console.error('---> [caseCLaimEdit.js] showFactorySummary Error ' + ex);
            console.error(JSON.stringify(ex));
            this.showToast(this.getMessage(ex), 'error');
        } finally {            
            this.isExecuting = false;
        }
    }   
    
    showToast(message, theme) {
        this.dispatchEvent(
            new ShowToastEvent({
                title: '',
                message: message,
                variant: theme,
                mode: 'dismissable'
            })
        );
    }

    getMessage(variable) {
        if (typeof variable === 'string') {
            return variable;
        }
        if (typeof variable === 'object' && variable !== null && ('message' in variable)) {
            return variable.message;
        }
        return JSON.stringify(variable);
    }
}