/*-----------------------------------------------------------------------------------------
Author:         Ivan Losilla Perez
Company:        Porcelanosa
Date:			01-06-2020
Description:    Test para la clase AccountActivity.
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Accounts
* @deprecated  We don't use this one
*/
@IsTest public class AccountActivityTest {
}