/*-----------------------------------------------------------------------------------------
Author:         Ivan Losilla Perez
Company:        Porcelanosa
Date:           26-05-2020
Description:    Manage the Account Team Members's Triggers
Test Class:     AccountTeamMemberHandler_Test
History
<Date>            <Author>              <Change Description>

-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Triggers
* @deprecated  We don't use this one, instead we use AccountTeamMemberTriggerHandler
*/
public class AccountTeamMemberHandler {}