/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Date:			21-03-2019
Description:    Administra el campo Number_Of_Contacts__c de Account. 
Test Class:     ContactHandlerTest
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Triggers
* @deprecated  We don't use this one, instead we useContactTriggerHandler
*/

public class ContactHandler{}