public with sharing class ModalResultFieldLabels {


    public static final String GLOBAL_NAME_FIELD_LABEL = Label.dict_name;
    public static final String GLOBAL_STREET_FIELD_LABEL = Label.dict_street;
    public static final String GLOBAL_POSTALCODE_FIELD_LABEL = Label.dict_postal_code;
    public static final String GLOBAL_CITY_FIELD_LABEL = Label.dict_city;
    public static final String GLOBAL_COUNTRY_FIELD_LABEL = Label.dict_country;
    public static final String GLOBAL_ADDRESS_FIELD_LABEL = Label.dict_address;


    // Specific fields labels for French account

    public static final String FR_SIRET_FIELD_LABEL = 'Siret';
    public static final String FR_SIREN_FIELD_LABEL = 'Siren';
    public static final String FR_SEARCH_BY_ID_LABEL = 'Siret/Siren';


}