/*-----------------------------------------------------------------------------------------
     Apex Class:        NB2B_TaxesCheckout
     Created Date:      16/02/2022
     Author:            Ignacio G. Schuhmacher
     Mail:              ignacio.galindo@nubika.com
     Description:       Taxes calculation
------------------------------------------------------------------------------------------*/
public with sharing class NB2B_TaxesCheckout{
    public static String loremIpsum() {
        string s = 'Lorem';
        s += 'Lorem';
        return s;
    }
}