/*-----------------------------------------------------------------------------------------
     Apex Class:        NB2B_AreaCalculationController
     Created Date:      12/01/2022
     Author:            Ignacio Galindo Schuhmacher
     Mail:              ignacio.galindo@nubika.com
     Description:       Class to manage show button conditions and Area calculations
------------------------------------------------------------------------------------------*/


public class NB2B_AreaCalculationController {
    public static String loremIpsum() {
        string s = 'Lorem';
        s += 'Lorem';
        return s;
    }	
}