/*-----------------------------------------------------------------------------------------
     Apex Class:        NB2B_ProductQuantitiesSummary
     Created Date:      16/02/2022
     Author:            Ignacio G. Schuhmacher
     Mail:              ignacio.galindo@nubika.com
     Description:       Order Item list summary
------------------------------------------------------------------------------------------*/
public without sharing class NB2B_ProductQuantitiesSummary {
    public static String loremIpsum() {
        string s = 'Lorem';
        s += 'Lorem';
        return s;
    }
}