/*-----------------------------------------------------------------------------------------
     Apex Class:        NB2B_SearchSku
     Created Date:      26/05/2022
     Author:            Ignacio Galindo Schuhmacher
     Mail:              ignacio.galindo@nubika.com
     Description:       Class to manage show button conditions and Area calculations
------------------------------------------------------------------------------------------*/

public class NB2B_SearchSku {
    public static String loremIpsum() {
        string s = 'Lorem';
        s += 'Lorem';
        return s;
    }
}