/*-----------------------------------------------------------------------------------------
     Apex Class:        NB2B_OrderSyncJob_Test
     Created Date:      01/09/2022
     Author:            Ignacio Galindo Schuhmacher
     Mail:              ignacio.galindo@nubika.com
     Description:       Batch dedicated to inserting / updating the records of the external 
------------------------------------------------------------------------------------------*/
@isTest
public class NB2B_QuickOrderTest {

}