/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Date:			28-03-2019
Description:    Test para la clase OpportunityActorHandler y el trigger OpportunityActorTrigger.
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Triggers
* @deprecated  We don't use this one, instead we use ContactTriggerHandlerTest
*/
@isTest 
public class OpportunityActorHandlerTest {}