public class OrganizationCommons {



    public static final String SOC_PIDF = '208';
    public static final String SOC_EUROCERAMIQUE = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('EUROCERAMIQUE SARL');
    public static final String SOC_LORCERAM = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('Azurceramique');
    public static final String SOC_SOCAMED = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('SOCAMED SARL');
    public static final String SOC_OUEST = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA OUEST SAS');
    public static final String SOC_SUD_OUEST = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA SUD-OUEST');
    
    public static final String SOC_SOUTH_EAST = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA SOUTHEAST LTD');
    public static final String SOC_NORTH_WEST = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA NORTHWEST LTD');
    public static final String SOC_MIDLANDS = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA MIDLANDS LTD');
    public static final String SOC_SCOTLAND = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA SCOTLAND LTD');
    public static final String SOC_WESTERN = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA WESTERN LTD');
    public static final String SOC_YORKSHIRE = PicklistCommons.getValuesSwaped(Account.Company_List__c).get('PORCELANOSA YORKSHIRE LTD');

   
    public static final String ORG_AZURCERAMIQUE = '226';
    public static final String ORG_LORCERAM = '227';
    public static final String ORG_EUROCERAMIQUE = '228';
    public static final String ORG_PIDF = '229';
    public static final String ORG_SOCAMED = '230';
    public static final String ORG_OUEST = '231';
    public static final String ORG_SUD_OUEST = '232';
    public static final String ORG_XTONE_FR = '225';

    public static final String ORG_SOUTH_EAST = '502';
    public static final String ORG_NORTH_WEST = '514';
    public static final String ORG_MIDLANDS = '515';
    public static final String ORG_SCOTLAND = '516';
    public static final String ORG_WESTERN = '517';
    public static final String ORG_YORKSHIRE = '518';
    public static final String ORG_XTONE_GB = '511';

    public static final String ORG_FLORIDA = '602';
    public static final String ORG_SAN_FRANCISCO = '604';
    public static final String ORG_LOS_ANGELES = '603';
    public static final String ORG_NEW_YORK = '605';
    public static final String ORG_TEXAS = '608';
    public static final String ORG_MARYLAND = '606';
    public static final String ORG_XTONE_US = '615';

    public static final String ORG_CANADA = '650';
}