/**
 * Trigger Handler for the ProductCaseHandler . This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
* @author gmiranda-NTS
* @date 02/05/2018
* @service Hecho por NTS
*/

public class ProductCaseHandler {}
// public class ProductCaseHandler implements ITrigger
// {
//     // Constructor
//     public ProductCaseHandler() {}
 
    /**
//      * bulkBefore
//      *
//      * These methods are called prior to execution of a BEFORE or AFTER trigger. Use this to cache
//      * any data required into maps prior execution of the trigger.
//      * Any new SOQL operation should be included in these methods (bulkBefore or bulkAfter)
//      */
//     /**
//     * @cases cuando prepararon Service
//     */
//     public void bulkBefore(list<SObject> newList, map<Id,SObject> oldMap)   {   }
    
// //     public void bulkAfter(list<SObject> newList, map<Id,SObject> oldMap)    {   }

//     /* These methods ara called for records to be processed during a BEFORE 
//      * trigger.
//      */
//     public void beforeInsert(list<SObject> newList)
//     {
//         /*ProductCaseUtil.obtainMaterialPrice((List<Product_Case__c>)newList);
//         ProductCaseUtil.updateFinalPrice((List<Product_Case__c>)newList,null);
//         ProductCaseUtil.updateParentCase((List<Product_Case__c>)newList);*/
//     }
    
//     public void beforeUpdate(list<SObject> newList, map<Id,SObject> oldMap)
//     {
//      	/*ProductCaseUtil.updateFinalPrice((List<Product_Case__c>)newList,(Map<Id,Product_Case__c>)oldMap);
//         ProductCaseUtil.updateParentCase((List<Product_Case__c>)newList);*/
//     }
    
//     public void beforeDelete(map<Id,SObject> oldMap)                        {   }
    
//     /**
//      * These methods ara called for records to be processed during a AFTER 
//      * trigger.
//      */ 
//     public void afterInsert(list<SObject> newList)                          {   }
     
//     public void afterUpdate(list<SObject> newList, map<Id,SObject> oldMap)  {   }
     
//     public void afterDelete(map<Id,SObject> oldMap)                         {   }
     
//     /**
//      * andFinally
//      *
//      * This method is called once all records have been processed by the trigger. Use this
//      * method to accomplish any final operations such as creation or updates of other records.
//      * Any new DML operation should be included in this method
//      */
//     public void andFinally()                                                {   }
// }