/*-----------------------------------------------------------------------------------------
Author:         Ivan Losilla Perez
Company:        Porcelanosa
Description:    Clase test de SalesRelationshipHandler
Date:			25-05-2020
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Triggers
* @deprecated We use SalesRelationshipTriggerHandlerTest instead
*/
@isTest
public class SalesRelationshipHandlerTest {}