/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Date:			27-02-2019
Description:    Test para la clase SalesRelationshipHandler y el trigger SalesRelationship_Trigger
Test Class:     SalesRelationship_TriggerHandlerTest
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @deprecated  We use SalesRelationshipTriggerHandlerTest
*/
@isTest
public class SalesRelationship_TriggerHandlerTest {}