/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Date:			21-03-2019
Description:    
Test Class:     SalesRelationship_TriggerHandlerTest
History
<Date>            <Author>              <Change Description>
22/03/19		Juan Manuel Martinez	Comprobar que no haya una oportunidad ya creada para la cuenta de la relacion de ventas.
17/05/19		Juan Manuel Martinez	Cambios de que record type crean oportunidades
27/05/19		Juan Manuel Martinez	Comentada la parte de account share
-----------------------------------------------------------------------------------------*/

/**
* @date September 2021
* @group Triggers
* @deprecated  We don't use this one, we use SalesRelationshipTriggerHandler instead
*/
public without sharing class SalesRelationshipHandler{}