/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Description:    Clase test de TaskHandler
Date:			21-03-2019
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @date September 2021
* @group Triggers
* @deprecated  We don't use this one, instead we use TaskTriggerHandlerTest
*/
@isTest
public class TaskHandlerTest {
}