/*-----------------------------------------------------------------------------------------
Author:         Juan Manuel Martinez
Company:        Neoris
Date:			25-04-2019
Description:    Test para la clase UpdateOpportunityActor
History
<Date>            <Author>              <Change Description>
-----------------------------------------------------------------------------------------*/
/**
* @deprecated January 2022 No se usa el componente de la clase
*/
@isTest
public class UpdateOpportunityActorTest {
}