/**
* @author Ivan Losilla
* @date April 2021
* @group Triggers
* @description Waiting List Trigger Handler
*/
public class WaitingListTriggerHandler extends BaseTriggerHandler {
    public override void beforeDelete(List<SObject> oldItems) {
    }

    public override void beforeUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
    }

    public override void afterUpdate(List<SObject> newItems, Map<Id, SObject> oldItems) {
    }
    
    public override void beforeInsert(List<SObject> newItems) {
    }
    
    public override void afterInsert(List<SObject> newItems) {
    }
}