/**
* @author 		Ramón Prades
* @date 		May 2022
* @group 		Exceptions
* @description 	General purpose domain layer exception (replaces fflib_SObjectDomain.DomainException in our adaptation of that framework).
*/
/*
 * WARNING:
 * This class is the adaptation to Porcelanosa of the Apex Commons Framework.
 * The framework has been adapted to pass the tests because of our required fields and
 * validation rules.
 * Only the classes we need have been adapted and are those prefixed with "zflib".
 * Ramón, May 2022
 */
public class zflib_DomainException extends Exception {
}